@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "123456"
}

###

# @name questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta 2",
    "content": "Conteúdo da nova pergunta "
}

###

# @name questions
GET  {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}